import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Static Indian states and districts data
const STATES = [
  { state_id: 1, state_name: 'Andhra Pradesh' },
  { state_id: 2, state_name: 'Arunachal Pradesh' },
  { state_id: 3, state_name: 'Assam' },
  { state_id: 4, state_name: 'Bihar' },
  { state_id: 5, state_name: 'Chhattisgarh' },
  { state_id: 6, state_name: 'Goa' },
  { state_id: 7, state_name: 'Gujarat' },
  { state_id: 8, state_name: 'Haryana' },
  { state_id: 9, state_name: 'Himachal Pradesh' },
  { state_id: 10, state_name: 'Jharkhand' },
  { state_id: 11, state_name: 'Karnataka' },
  { state_id: 12, state_name: 'Kerala' },
  { state_id: 13, state_name: 'Madhya Pradesh' },
  { state_id: 14, state_name: 'Maharashtra' },
  { state_id: 15, state_name: 'Manipur' },
  { state_id: 16, state_name: 'Meghalaya' },
  { state_id: 17, state_name: 'Mizoram' },
  { state_id: 18, state_name: 'Nagaland' },
  { state_id: 19, state_name: 'Odisha' },
  { state_id: 20, state_name: 'Punjab' },
  { state_id: 21, state_name: 'Rajasthan' },
  { state_id: 22, state_name: 'Sikkim' },
  { state_id: 23, state_name: 'Tamil Nadu' },
  { state_id: 24, state_name: 'Telangana' },
  { state_id: 25, state_name: 'Tripura' },
  { state_id: 26, state_name: 'Uttar Pradesh' },
  { state_id: 27, state_name: 'Uttarakhand' },
  { state_id: 28, state_name: 'West Bengal' },
  { state_id: 29, state_name: 'Andaman and Nicobar Islands' },
  { state_id: 30, state_name: 'Chandigarh' },
  { state_id: 31, state_name: 'Dadra and Nagar Haveli and Daman and Diu' },
  { state_id: 32, state_name: 'Delhi' },
  { state_id: 33, state_name: 'Jammu and Kashmir' },
  { state_id: 34, state_name: 'Ladakh' },
  { state_id: 35, state_name: 'Lakshadweep' },
  { state_id: 36, state_name: 'Puducherry' },
];

const DISTRICTS: Record<number, Array<{ district_id: number; district_name: string }>> = {
  1: [ // Andhra Pradesh
    { district_id: 101, district_name: 'Alluri Sitharama Raju' },
    { district_id: 102, district_name: 'Anakapalli' },
    { district_id: 103, district_name: 'Anantapur' },
    { district_id: 104, district_name: 'Bapatla' },
    { district_id: 105, district_name: 'Chittoor' },
    { district_id: 106, district_name: 'Dr. B.R. Ambedkar Konaseema' },
    { district_id: 107, district_name: 'East Godavari' },
    { district_id: 108, district_name: 'Eluru' },
    { district_id: 109, district_name: 'Guntur' },
    { district_id: 110, district_name: 'Kadapa' },
    { district_id: 111, district_name: 'Kakinada' },
    { district_id: 112, district_name: 'Krishna' },
    { district_id: 113, district_name: 'Kurnool' },
    { district_id: 114, district_name: 'Nandyal' },
    { district_id: 115, district_name: 'NTR' },
    { district_id: 116, district_name: 'Palnadu' },
    { district_id: 117, district_name: 'Parvathipuram Manyam' },
    { district_id: 118, district_name: 'Prakasam' },
    { district_id: 119, district_name: 'Sri Potti Sri Ramulu Nellore' },
    { district_id: 120, district_name: 'Sri Sathya Sai' },
    { district_id: 121, district_name: 'Srikakulam' },
    { district_id: 122, district_name: 'Tirupati' },
    { district_id: 123, district_name: 'Visakhapatnam' },
    { district_id: 124, district_name: 'Vizianagaram' },
    { district_id: 125, district_name: 'West Godavari' },
  ],
  11: [ // Karnataka
    { district_id: 1101, district_name: 'Bagalkot' },
    { district_id: 1102, district_name: 'Ballari' },
    { district_id: 1103, district_name: 'Belagavi' },
    { district_id: 1104, district_name: 'Bengaluru Rural' },
    { district_id: 1105, district_name: 'Bengaluru Urban' },
    { district_id: 1106, district_name: 'Bidar' },
    { district_id: 1107, district_name: 'Chamarajanagar' },
    { district_id: 1108, district_name: 'Chikkaballapur' },
    { district_id: 1109, district_name: 'Chikkamagaluru' },
    { district_id: 1110, district_name: 'Chitradurga' },
    { district_id: 1111, district_name: 'Dakshina Kannada' },
    { district_id: 1112, district_name: 'Davangere' },
    { district_id: 1113, district_name: 'Dharwad' },
    { district_id: 1114, district_name: 'Gadag' },
    { district_id: 1115, district_name: 'Hassan' },
    { district_id: 1116, district_name: 'Haveri' },
    { district_id: 1117, district_name: 'Kalaburagi' },
    { district_id: 1118, district_name: 'Kodagu' },
    { district_id: 1119, district_name: 'Kolar' },
    { district_id: 1120, district_name: 'Koppal' },
    { district_id: 1121, district_name: 'Mandya' },
    { district_id: 1122, district_name: 'Mysuru' },
    { district_id: 1123, district_name: 'Raichur' },
    { district_id: 1124, district_name: 'Ramanagara' },
    { district_id: 1125, district_name: 'Shivamogga' },
    { district_id: 1126, district_name: 'Tumakuru' },
    { district_id: 1127, district_name: 'Udupi' },
    { district_id: 1128, district_name: 'Uttara Kannada' },
    { district_id: 1129, district_name: 'Vijayapura' },
    { district_id: 1130, district_name: 'Yadgir' },
  ],
  12: [ // Kerala
    { district_id: 1201, district_name: 'Alappuzha' },
    { district_id: 1202, district_name: 'Ernakulam' },
    { district_id: 1203, district_name: 'Idukki' },
    { district_id: 1204, district_name: 'Kannur' },
    { district_id: 1205, district_name: 'Kasaragod' },
    { district_id: 1206, district_name: 'Kollam' },
    { district_id: 1207, district_name: 'Kottayam' },
    { district_id: 1208, district_name: 'Kozhikode' },
    { district_id: 1209, district_name: 'Malappuram' },
    { district_id: 1210, district_name: 'Palakkad' },
    { district_id: 1211, district_name: 'Pathanamthitta' },
    { district_id: 1212, district_name: 'Thiruvananthapuram' },
    { district_id: 1213, district_name: 'Thrissur' },
    { district_id: 1214, district_name: 'Wayanad' },
  ],
  13: [ // Madhya Pradesh
    { district_id: 1301, district_name: 'Agar Malwa' },
    { district_id: 1302, district_name: 'Alirajpur' },
    { district_id: 1303, district_name: 'Anuppur' },
    { district_id: 1304, district_name: 'Ashoknagar' },
    { district_id: 1305, district_name: 'Balaghat' },
    { district_id: 1306, district_name: 'Barwani' },
    { district_id: 1307, district_name: 'Betul' },
    { district_id: 1308, district_name: 'Bhind' },
    { district_id: 1309, district_name: 'Bhopal' },
    { district_id: 1310, district_name: 'Burhanpur' },
    { district_id: 1311, district_name: 'Chhatarpur' },
    { district_id: 1312, district_name: 'Chhindwara' },
    { district_id: 1313, district_name: 'Damoh' },
    { district_id: 1314, district_name: 'Datia' },
    { district_id: 1315, district_name: 'Dewas' },
    { district_id: 1316, district_name: 'Dhar' },
    { district_id: 1317, district_name: 'Dindori' },
    { district_id: 1318, district_name: 'Guna' },
    { district_id: 1319, district_name: 'Gwalior' },
    { district_id: 1320, district_name: 'Harda' },
    { district_id: 1321, district_name: 'Indore' },
    { district_id: 1322, district_name: 'Jabalpur' },
    { district_id: 1323, district_name: 'Jhabua' },
    { district_id: 1324, district_name: 'Katni' },
    { district_id: 1325, district_name: 'Khandwa' },
    { district_id: 1326, district_name: 'Khargone' },
    { district_id: 1327, district_name: 'Mandla' },
    { district_id: 1328, district_name: 'Mandsaur' },
    { district_id: 1329, district_name: 'Morena' },
    { district_id: 1330, district_name: 'Narsinghpur' },
    { district_id: 1331, district_name: 'Neemuch' },
    { district_id: 1332, district_name: 'Niwari' },
    { district_id: 1333, district_name: 'Panna' },
    { district_id: 1334, district_name: 'Raisen' },
    { district_id: 1335, district_name: 'Rajgarh' },
    { district_id: 1336, district_name: 'Ratlam' },
    { district_id: 1337, district_name: 'Rewa' },
    { district_id: 1338, district_name: 'Sagar' },
    { district_id: 1339, district_name: 'Satna' },
    { district_id: 1340, district_name: 'Sehore' },
    { district_id: 1341, district_name: 'Seoni' },
    { district_id: 1342, district_name: 'Shahdol' },
    { district_id: 1343, district_name: 'Shajapur' },
    { district_id: 1344, district_name: 'Sheopur' },
    { district_id: 1345, district_name: 'Shivpuri' },
    { district_id: 1346, district_name: 'Sidhi' },
    { district_id: 1347, district_name: 'Singrauli' },
    { district_id: 1348, district_name: 'Tikamgarh' },
    { district_id: 1349, district_name: 'Ujjain' },
    { district_id: 1350, district_name: 'Umaria' },
    { district_id: 1351, district_name: 'Vidisha' },
  ],
  14: [ // Maharashtra
    { district_id: 1401, district_name: 'Ahmednagar' },
    { district_id: 1402, district_name: 'Akola' },
    { district_id: 1403, district_name: 'Amravati' },
    { district_id: 1404, district_name: 'Aurangabad' },
    { district_id: 1405, district_name: 'Beed' },
    { district_id: 1406, district_name: 'Bhandara' },
    { district_id: 1407, district_name: 'Buldhana' },
    { district_id: 1408, district_name: 'Chandrapur' },
    { district_id: 1409, district_name: 'Dhule' },
    { district_id: 1410, district_name: 'Gadchiroli' },
    { district_id: 1411, district_name: 'Gondia' },
    { district_id: 1412, district_name: 'Hingoli' },
    { district_id: 1413, district_name: 'Jalgaon' },
    { district_id: 1414, district_name: 'Jalna' },
    { district_id: 1415, district_name: 'Kolhapur' },
    { district_id: 1416, district_name: 'Latur' },
    { district_id: 1417, district_name: 'Mumbai City' },
    { district_id: 1418, district_name: 'Mumbai Suburban' },
    { district_id: 1419, district_name: 'Nagpur' },
    { district_id: 1420, district_name: 'Nanded' },
    { district_id: 1421, district_name: 'Nandurbar' },
    { district_id: 1422, district_name: 'Nashik' },
    { district_id: 1423, district_name: 'Osmanabad' },
    { district_id: 1424, district_name: 'Palghar' },
    { district_id: 1425, district_name: 'Parbhani' },
    { district_id: 1426, district_name: 'Pune' },
    { district_id: 1427, district_name: 'Raigad' },
    { district_id: 1428, district_name: 'Ratnagiri' },
    { district_id: 1429, district_name: 'Sangli' },
    { district_id: 1430, district_name: 'Satara' },
    { district_id: 1431, district_name: 'Sindhudurg' },
    { district_id: 1432, district_name: 'Solapur' },
    { district_id: 1433, district_name: 'Thane' },
    { district_id: 1434, district_name: 'Wardha' },
    { district_id: 1435, district_name: 'Washim' },
    { district_id: 1436, district_name: 'Yavatmal' },
  ],
  23: [ // Tamil Nadu
    { district_id: 2301, district_name: 'Ariyalur' },
    { district_id: 2302, district_name: 'Chengalpattu' },
    { district_id: 2303, district_name: 'Chennai' },
    { district_id: 2304, district_name: 'Coimbatore' },
    { district_id: 2305, district_name: 'Cuddalore' },
    { district_id: 2306, district_name: 'Dharmapuri' },
    { district_id: 2307, district_name: 'Dindigul' },
    { district_id: 2308, district_name: 'Erode' },
    { district_id: 2309, district_name: 'Kallakurichi' },
    { district_id: 2310, district_name: 'Kancheepuram' },
    { district_id: 2311, district_name: 'Kanyakumari' },
    { district_id: 2312, district_name: 'Karur' },
    { district_id: 2313, district_name: 'Krishnagiri' },
    { district_id: 2314, district_name: 'Madurai' },
    { district_id: 2315, district_name: 'Mayiladuthurai' },
    { district_id: 2316, district_name: 'Nagapattinam' },
    { district_id: 2317, district_name: 'Namakkal' },
    { district_id: 2318, district_name: 'Nilgiris' },
    { district_id: 2319, district_name: 'Perambalur' },
    { district_id: 2320, district_name: 'Pudukkottai' },
    { district_id: 2321, district_name: 'Ramanathapuram' },
    { district_id: 2322, district_name: 'Ranipet' },
    { district_id: 2323, district_name: 'Salem' },
    { district_id: 2324, district_name: 'Sivaganga' },
    { district_id: 2325, district_name: 'Tenkasi' },
    { district_id: 2326, district_name: 'Thanjavur' },
    { district_id: 2327, district_name: 'Theni' },
    { district_id: 2328, district_name: 'Thoothukudi' },
    { district_id: 2329, district_name: 'Tiruchirappalli' },
    { district_id: 2330, district_name: 'Tirunelveli' },
    { district_id: 2331, district_name: 'Tirupathur' },
    { district_id: 2332, district_name: 'Tiruppur' },
    { district_id: 2333, district_name: 'Tiruvallur' },
    { district_id: 2334, district_name: 'Tiruvannamalai' },
    { district_id: 2335, district_name: 'Tiruvarur' },
    { district_id: 2336, district_name: 'Vellore' },
    { district_id: 2337, district_name: 'Viluppuram' },
    { district_id: 2338, district_name: 'Virudhunagar' },
  ],
  24: [ // Telangana
    { district_id: 2401, district_name: 'Adilabad' },
    { district_id: 2402, district_name: 'Bhadradri Kothagudem' },
    { district_id: 2403, district_name: 'Hanumakonda' },
    { district_id: 2404, district_name: 'Hyderabad' },
    { district_id: 2405, district_name: 'Jagtial' },
    { district_id: 2406, district_name: 'Jangaon' },
    { district_id: 2407, district_name: 'Jayashankar Bhupalpally' },
    { district_id: 2408, district_name: 'Jogulamba Gadwal' },
    { district_id: 2409, district_name: 'Kamareddy' },
    { district_id: 2410, district_name: 'Karimnagar' },
    { district_id: 2411, district_name: 'Khammam' },
    { district_id: 2412, district_name: 'Kumuram Bheem Asifabad' },
    { district_id: 2413, district_name: 'Mahabubabad' },
    { district_id: 2414, district_name: 'Mahabubnagar' },
    { district_id: 2415, district_name: 'Mancherial' },
    { district_id: 2416, district_name: 'Medak' },
    { district_id: 2417, district_name: 'Medchal-Malkajgiri' },
    { district_id: 2418, district_name: 'Mulugu' },
    { district_id: 2419, district_name: 'Nagarkurnool' },
    { district_id: 2420, district_name: 'Nalgonda' },
    { district_id: 2421, district_name: 'Narayanpet' },
    { district_id: 2422, district_name: 'Nirmal' },
    { district_id: 2423, district_name: 'Nizamabad' },
    { district_id: 2424, district_name: 'Peddapalli' },
    { district_id: 2425, district_name: 'Rajanna Sircilla' },
    { district_id: 2426, district_name: 'Rangareddy' },
    { district_id: 2427, district_name: 'Sangareddy' },
    { district_id: 2428, district_name: 'Siddipet' },
    { district_id: 2429, district_name: 'Suryapet' },
    { district_id: 2430, district_name: 'Vikarabad' },
    { district_id: 2431, district_name: 'Wanaparthy' },
    { district_id: 2432, district_name: 'Warangal' },
    { district_id: 2433, district_name: 'Yadadri Bhuvanagiri' },
  ],
  26: [ // Uttar Pradesh
    { district_id: 2601, district_name: 'Agra' },
    { district_id: 2602, district_name: 'Aligarh' },
    { district_id: 2603, district_name: 'Ambedkar Nagar' },
    { district_id: 2604, district_name: 'Amethi' },
    { district_id: 2605, district_name: 'Amroha' },
    { district_id: 2606, district_name: 'Auraiya' },
    { district_id: 2607, district_name: 'Ayodhya' },
    { district_id: 2608, district_name: 'Azamgarh' },
    { district_id: 2609, district_name: 'Baghpat' },
    { district_id: 2610, district_name: 'Bahraich' },
    { district_id: 2611, district_name: 'Ballia' },
    { district_id: 2612, district_name: 'Balrampur' },
    { district_id: 2613, district_name: 'Banda' },
    { district_id: 2614, district_name: 'Barabanki' },
    { district_id: 2615, district_name: 'Bareilly' },
    { district_id: 2616, district_name: 'Basti' },
    { district_id: 2617, district_name: 'Bhadohi' },
    { district_id: 2618, district_name: 'Bijnor' },
    { district_id: 2619, district_name: 'Budaun' },
    { district_id: 2620, district_name: 'Bulandshahr' },
    { district_id: 2621, district_name: 'Chandauli' },
    { district_id: 2622, district_name: 'Chitrakoot' },
    { district_id: 2623, district_name: 'Deoria' },
    { district_id: 2624, district_name: 'Etah' },
    { district_id: 2625, district_name: 'Etawah' },
    { district_id: 2626, district_name: 'Farrukhabad' },
    { district_id: 2627, district_name: 'Fatehpur' },
    { district_id: 2628, district_name: 'Firozabad' },
    { district_id: 2629, district_name: 'Gautam Buddha Nagar' },
    { district_id: 2630, district_name: 'Ghaziabad' },
    { district_id: 2631, district_name: 'Ghazipur' },
    { district_id: 2632, district_name: 'Gonda' },
    { district_id: 2633, district_name: 'Gorakhpur' },
    { district_id: 2634, district_name: 'Hamirpur' },
    { district_id: 2635, district_name: 'Hapur' },
    { district_id: 2636, district_name: 'Hardoi' },
    { district_id: 2637, district_name: 'Hathras' },
    { district_id: 2638, district_name: 'Jalaun' },
    { district_id: 2639, district_name: 'Jaunpur' },
    { district_id: 2640, district_name: 'Jhansi' },
    { district_id: 2641, district_name: 'Kannauj' },
    { district_id: 2642, district_name: 'Kanpur Dehat' },
    { district_id: 2643, district_name: 'Kanpur Nagar' },
    { district_id: 2644, district_name: 'Kasganj' },
    { district_id: 2645, district_name: 'Kaushambi' },
    { district_id: 2646, district_name: 'Kushinagar' },
    { district_id: 2647, district_name: 'Lakhimpur Kheri' },
    { district_id: 2648, district_name: 'Lalitpur' },
    { district_id: 2649, district_name: 'Lucknow' },
    { district_id: 2650, district_name: 'Maharajganj' },
    { district_id: 2651, district_name: 'Mahoba' },
    { district_id: 2652, district_name: 'Mainpuri' },
    { district_id: 2653, district_name: 'Mathura' },
    { district_id: 2654, district_name: 'Mau' },
    { district_id: 2655, district_name: 'Meerut' },
    { district_id: 2656, district_name: 'Mirzapur' },
    { district_id: 2657, district_name: 'Moradabad' },
    { district_id: 2658, district_name: 'Muzaffarnagar' },
    { district_id: 2659, district_name: 'Pilibhit' },
    { district_id: 2660, district_name: 'Pratapgarh' },
    { district_id: 2661, district_name: 'Prayagraj' },
    { district_id: 2662, district_name: 'Rae Bareli' },
    { district_id: 2663, district_name: 'Rampur' },
    { district_id: 2664, district_name: 'Saharanpur' },
    { district_id: 2665, district_name: 'Sambhal' },
    { district_id: 2666, district_name: 'Sant Kabir Nagar' },
    { district_id: 2667, district_name: 'Shahjahanpur' },
    { district_id: 2668, district_name: 'Shamli' },
    { district_id: 2669, district_name: 'Shrawasti' },
    { district_id: 2670, district_name: 'Siddharthnagar' },
    { district_id: 2671, district_name: 'Sitapur' },
    { district_id: 2672, district_name: 'Sonbhadra' },
    { district_id: 2673, district_name: 'Sultanpur' },
    { district_id: 2674, district_name: 'Unnao' },
    { district_id: 2675, district_name: 'Varanasi' },
  ],
  28: [ // West Bengal
    { district_id: 2801, district_name: 'Alipurduar' },
    { district_id: 2802, district_name: 'Bankura' },
    { district_id: 2803, district_name: 'Birbhum' },
    { district_id: 2804, district_name: 'Cooch Behar' },
    { district_id: 2805, district_name: 'Dakshin Dinajpur' },
    { district_id: 2806, district_name: 'Darjeeling' },
    { district_id: 2807, district_name: 'Hooghly' },
    { district_id: 2808, district_name: 'Howrah' },
    { district_id: 2809, district_name: 'Jalpaiguri' },
    { district_id: 2810, district_name: 'Jhargram' },
    { district_id: 2811, district_name: 'Kalimpong' },
    { district_id: 2812, district_name: 'Kolkata' },
    { district_id: 2813, district_name: 'Malda' },
    { district_id: 2814, district_name: 'Murshidabad' },
    { district_id: 2815, district_name: 'Nadia' },
    { district_id: 2816, district_name: 'North 24 Parganas' },
    { district_id: 2817, district_name: 'Paschim Bardhaman' },
    { district_id: 2818, district_name: 'Paschim Medinipur' },
    { district_id: 2819, district_name: 'Purba Bardhaman' },
    { district_id: 2820, district_name: 'Purba Medinipur' },
    { district_id: 2821, district_name: 'Purulia' },
    { district_id: 2822, district_name: 'South 24 Parganas' },
    { district_id: 2823, district_name: 'Uttar Dinajpur' },
  ],
  32: [ // Delhi
    { district_id: 3201, district_name: 'Central Delhi' },
    { district_id: 3202, district_name: 'East Delhi' },
    { district_id: 3203, district_name: 'New Delhi' },
    { district_id: 3204, district_name: 'North Delhi' },
    { district_id: 3205, district_name: 'North East Delhi' },
    { district_id: 3206, district_name: 'North West Delhi' },
    { district_id: 3207, district_name: 'Shahdara' },
    { district_id: 3208, district_name: 'South Delhi' },
    { district_id: 3209, district_name: 'South East Delhi' },
    { district_id: 3210, district_name: 'South West Delhi' },
    { district_id: 3211, district_name: 'West Delhi' },
  ],
};

// Default districts for states not explicitly listed
function getDefaultDistricts(stateId: number, stateName: string) {
  return [
    { district_id: stateId * 100 + 1, district_name: `${stateName} District 1` },
    { district_id: stateId * 100 + 2, district_name: `${stateName} District 2` },
    { district_id: stateId * 100 + 3, district_name: `${stateName} District 3` },
  ];
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const type = url.searchParams.get('type') || '';
    const stateId = parseInt(url.searchParams.get('state_id') || '0');

    if (type === 'states') {
      return new Response(JSON.stringify({ states: STATES }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    if (type === 'districts' && stateId) {
      const state = STATES.find(s => s.state_id === stateId);
      const districts = DISTRICTS[stateId] || (state ? getDefaultDistricts(stateId, state.state_name) : []);
      return new Response(JSON.stringify({ districts }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    return new Response(JSON.stringify({ error: 'Invalid parameters' }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: String(error) }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
